import ProjectDescription
import ProjectDescriptionHelpers
import MyPlugin
import Foundation



// MARK: - Project
let tuistDependencies =  ProcessInfo.processInfo.environment["TUIST_EXCEPT_FRAMEWORK"]
let isExceptDepen = (tuistDependencies == "Y")

// Local plugin loaded
let localHelper = LocalHelper(name: "MyPlugin")

// Creates our project using a helper function defined in ProjectDescriptionHelpers
let workspace = Workspace(
    name: "MyApp",
    projects: [
        "Projects/MyApp",
        "Projects/MyAppKit",
        "Projects/MyAppUI"
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .relevant
        )
    )
)
