import ProjectDescription
import ProjectDescriptionHelpers
import MyPlugin
import Foundation



// MARK: - WorkSpace

// Local plugin loaded
let localHelper = LocalHelper(name: "MyPlugin")

// Creates our project using a helper function defined in ProjectDescriptionHelpers
let workspace = Workspace(
    name: "Application",
    projects: [
        "Projects/Application",
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .all // relevant -> all
        )
    )
)
